icon0 := "DALL·E 2025-03-07 11.57.52 - A modern app icon featuring a database cylinder combined with a line chart or bar graph overlay. The design should be sleek, minimalist, and use a vib.webp"
all:
	convert $(icon0) -define icon:auto-resize=256,64,48,32,16 icon.ico

