name: Publish Artifacts to Gitlab (MSU)

on:
  release:
    types:
      - released

jobs:
  publish-to-gitlab:
    name: Publish a New Release to MSU Gitlab
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .\wfdata\pkg\win\output

      - name: List artifacts
        run: ls -lhtr .\wfdata\pkg\win\output



